# List of dictionaries to use for spell checking
# Default: ["en_us"]
# Available dictionaries:
#  - English: "en_us", "en_gb"
#  - German: "de", "de_at", "de_ch"
#  - Spanish: "es"
#  - French: "fr"
#  - Italian: "it"
#  - Russian: "ru"
#  - Swedish: "sv"
dictionaries = ["en_us", "en_gb"]

# Custom allowlist of words to ignore (case-insensitive)
# Codebook will add words here when you select "Add to dictionary"
# Default: []
words = ["codebook", "rustc"]

# Words that should always be flagged as incorrect
# Default: []
flag_words = ["todo", "fixme"]

# List of glob patterns for paths to ignore when spell checking
# Default: []
ignore_paths = ["target/**/*", "**/*.json", ".git/**/*"]

# List of regex patterns to ignore when spell checking
# Patterns are matched against each line of text, not individual words
# Useful for domain-specific strings or patterns
# Note: Backslashes must be escaped in TOML (use \\ instead of \)
# Default: []
ignore_patterns = [
    "implicits",
    "\\b[ATCG]+\\b",             # DNA sequences
    "\\d{3}-\\d{2}-\\d{4}",      # Social Security Number format
    "^[A-Z]{2,}$",               # All caps words like "HTML", "CSS"
    "https?://[^\\s]+"           # URLs
]

# Whether to use global configuration (project config only)
# Set to false to completely ignore global settings
# Default: true
use_global = true
