#!/usr/bin/env sh

# Description: Navigate to directory using zoxide
#
# Dependencies:
#   - OR zoxide - https://github.com/ajeetdsouza/zoxide
#
# Shell: POSIX compliant
# Authors: Marty Buchaus, Dave Snider, Tim Adler, Nick Waywood

if [ ! -p "$NNN_PIPE" ]; then
    printf 'ERROR: NNN_PIPE is not set!'
    read -r _
    exit 2
fi

if type zoxide >/dev/null 2>&1; then
    if type fzf >/dev/null 2>&1; then
    	odir="$(zoxide query -l | fzf --tmux 85% --preview 'exa -la --header {}' --)"
    	printf "%s" "0c$odir" > "$NNN_PIPE"
    else
	printf "jump to : "
    	read -r dir
    	odir="$(zoxide query -- "$dir")"
    	printf "%s" "0c$odir" > "$NNN_PIPE"
    fi
fi
